use std::fmt;
use std::os::unix::process::CommandExt;
use std::path::Path;
use std::path::PathBuf;
use std::process::Command;

use crate::config::{RelativeHomePath, RelativeHomePathError};
use crate::error::NythError;
use crate::sys::namespace::{CallerIdentity, enter_isolated_session};
use crate::sys::overlay::{
    mount_home_snapshot, mount_overlay, provision_scratch_tmpfs, resolve_watched_paths,
};
use crate::sys::paths::{NythPaths, resolve_identity_and_paths};

/// The overlay session's lifecycle: mounted -> unmounted
#[derive(Debug, Clone)]
pub enum SessionState {
    Mounted {
        lower_dir: PathBuf,
        upper_dir: PathBuf,
        work_dir: PathBuf,
        home_target: PathBuf,
    },
    Unmounted {
        upper_dir: PathBuf,
    },
}

/// argv-parsed inputs to `nyth session`, everything the wrapper generated by the Home Manager module passes in
#[derive(Debug, Clone, Default)]
pub struct SessionArgs {
    pub watched_paths: Vec<RelativeHomePath>,
    pub env_overrides: Vec<(String, String)>,
    pub target_command: Vec<String>,
}

#[derive(Debug)]
pub enum SessionArgsError {
    MissingFlagValue {
        flag: &'static str,
    },
    InvalidWatchedPath {
        raw: String,
        source: RelativeHomePathError,
    },
    EnvNotKeyValue {
        raw: String,
    },
    UnexpectedArgument {
        raw: String,
    },
    MissingCommandSeparator,
}

impl fmt::Display for SessionArgsError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::MissingFlagValue { flag } => write!(f, "{flag} requires a value"),
            Self::InvalidWatchedPath { raw, source } => {
                write!(f, "invalid --watched-path '{raw}': {source}")
            }
            Self::EnvNotKeyValue { raw } => {
                write!(f, "--env value '{raw}' is not in KEY=VALUE form")
            }
            Self::UnexpectedArgument { raw } => write!(
                f,
                "unexpected argument '{raw}', expected --watched-path, --env, or '--'"
            ),
            Self::MissingCommandSeparator => {
                write!(f, "missing '--' separator before the target command")
            }
        }
    }
}

impl std::error::Error for SessionArgsError {}

/// Parses `nyth session [--watched-path <rel>]... [--env KEY=VALUE]... -- <command>...`
/// Wrapper generated by the Home Manager module's only contract with the `nyth` binary, so it's the sole place that turns raw argv into `SessionArgs`
pub fn parse_session_args(args: &[String]) -> Result<SessionArgs, SessionArgsError> {
    let mut parsed = SessionArgs::default();
    let mut remaining = args.iter();

    while let Some(arg) = remaining.next() {
        match arg.as_str() {
            "--watched-path" => {
                let raw = remaining.next().ok_or(SessionArgsError::MissingFlagValue {
                    flag: "--watched-path",
                })?;
                let path = RelativeHomePath::new(raw.as_str()).map_err(|source| {
                    SessionArgsError::InvalidWatchedPath {
                        raw: raw.clone(),
                        source,
                    }
                })?;
                parsed.watched_paths.push(path);
            }
            "--env" => {
                let raw = remaining
                    .next()
                    .ok_or(SessionArgsError::MissingFlagValue { flag: "--env" })?;
                let (key, value) = raw
                    .split_once('=')
                    .ok_or_else(|| SessionArgsError::EnvNotKeyValue { raw: raw.clone() })?;
                parsed
                    .env_overrides
                    .push((key.to_string(), value.to_string()));
            }
            "--" => {
                parsed.target_command = remaining.cloned().collect();
                return Ok(parsed);
            }
            other => {
                return Err(SessionArgsError::UnexpectedArgument {
                    raw: other.to_string(),
                });
            }
        }
    }

    Err(SessionArgsError::MissingCommandSeparator)
}

/// Resolves the caller's identity/paths and runs the session
/// Thin wrapper around `run_session_with`, same split as before
pub fn run_session(
    watched_paths: &[RelativeHomePath],
    env_overrides: &[(String, String)],
    target_command: &[String],
) -> NythError {
    if target_command.is_empty() {
        return NythError::NoTargetCommand;
    }

    let (identity, paths) = match resolve_identity_and_paths() {
        Ok(pair) => pair,
        Err(e) => return e,
    };

    run_session_with(
        watched_paths,
        env_overrides,
        target_command,
        &identity,
        &paths,
    )
}

/// Same as `run_session`, but takes `identity`/`paths` instead of computing them from the real process
pub fn run_session_with(
    watched_paths: &[RelativeHomePath],
    env_overrides: &[(String, String)],
    target_command: &[String],
    identity: &CallerIdentity,
    paths: &NythPaths,
) -> NythError {
    if let Err(e) = enter_isolated_session(identity.uid, identity.gid) {
        return NythError::Namespace(e);
    }

    let scratch = match provision_scratch_tmpfs(identity) {
        Ok(scratch) => scratch,
        Err(e) => return NythError::Overlay(e),
    };

    if let Err(e) = mount_home_snapshot(&identity.home, &scratch) {
        return NythError::Overlay(e);
    }

    if let Err(e) = ensure_dir(&paths.lower) {
        return e;
    }
    if let Err(e) = resolve_watched_paths(&scratch, &paths.lower, watched_paths) {
        return NythError::Overlay(e);
    }

    if let Err(e) = ensure_dir(&paths.upper) {
        return e;
    }
    if let Err(e) = ensure_dir(&paths.work) {
        return e;
    }

    if let Err(e) = mount_overlay(
        &paths.lower,
        &paths.upper,
        &paths.work,
        &scratch,
        &identity.home,
    ) {
        return NythError::Overlay(e);
    }

    exec_target(target_command, env_overrides)
}

// lower/upper/work are persistent, so unlike scratch's own subdirs they might not exist yet the very first time a session runs for this identity
fn ensure_dir(path: &Path) -> Result<(), NythError> {
    std::fs::create_dir_all(path).map_err(|e| NythError::SessionIoFailed {
        path: path.to_path_buf(),
        message: e.to_string(),
    })
}

// Only returns on failure: on success execvp() replaces this process image and this function stops existing
fn exec_target(command: &[String], env_overrides: &[(String, String)]) -> NythError {
    let Some((program, args)) = command.split_first() else {
        return NythError::NoTargetCommand;
    };

    let error = Command::new(program)
        .args(args)
        .envs(env_overrides.iter().cloned())
        .exec();
    NythError::ExecFailed {
        program: program.clone(),
        message: error.to_string(),
    }
}
